### ISSUE TITLE
Server Error when running frontend.process on mathlib4

### ISSUE THREAD

**Issue by sorgfresser** [lenianiva/PyPantograph#44]
I successfully built mathlib4, started the PyPantograph server on it and ran tactic invocations on the file `Mathlib/ModelTheory/Syntax.lean`. This resulted in 
```python3
  File "<...>/PyPantograph/pantograph/server.py", line 244, in tactic_invocations
    raise ServerError(result["desc"])
pantograph.server.ServerError: unknown constant 'term.pseudo.antiquot'
```

This is especially interesting because the term in question is not even mentioned in the whole file.

**Comment by lenianiva** [comment]
What version of mathlib are you using?

Mathlib4 seem to have this issue internally

**Comment by sorgfresser** [comment]
My version is new enough to suffer from this, I'll try downgrading and report back!

**Comment by lenianiva** [comment]
> My version is new enough to suffer from this, I'll try downgrading and report back!

Can you use the v4.12 tag of mathlib?

**Comment by sorgfresser** [comment]
Facing the same error on tag v4.12 upon running frontend.process on file `mathlib/Mathlib/ModelTheory/Syntax.lean`

**Comment by lenianiva** [comment]
Fixed in upstream: https://git.leni.sh/aniva/Pantograph/pulls/128

**Comment by lenianiva** [comment]
This PR helped me and others track down another bug in Lean 4: https://leanprover.zulipchat.com/#narrow/channel/270676-lean4/topic/What.20is.20.60term.2Epseudo.2Eantiquot.60.3F/near/487319979

**Comment by sorgfresser** [comment]
Awesome, thanks!

> This PR helped me and others track down another bug in Lean 4: https://leanprover.zulipchat.com/#narrow/channel/270676-lean4/topic/What.20is.20.60term.2Epseudo.2Eantiquot.60.3F/near/487319979
I was wondering what exactly happened, interesting to see it is actually related to Lean.
