### ISSUE TITLE
Issue for Mathlib Data Extraction

### ISSUE THREAD

**Issue by wclsn** [lenianiva/PyPantograph#55]
# Description
Very impressive work! I have tried to interact with LEAN and traced the internal information using PyPantoGraph. It is faster than existing tools and easier to use. However, when I used it to trace the Mathlib, I came across several issues, such as 
"Cannot decode: libc++abi: terminating due to uncaught exception of type lean::exception: cannot evaluate `[init]` declaration 'Mathlib.AssertNotExist.assertExistsExt' in the same module"
# Environment
Ubuntu 22.04
Python 3.10
git clone https://github.com/leanprover-community/mathlib4.git
cd mathlib4
git checkout  809c3fb3b5c8f5d7dace56e200b426187516535a  # Corresponding Lean Version : v4.12.0
Install the PantoGraph following the instructions in README

# Steps to Reproduce this Issue
```python
import os
import multiprocessing
from tqdm import tqdm
from pantograph import Server
def trace_file(file_path):
    server = Server(imports=[""], project_path="working_directory/mathlib4")
    res = []
    error_files = []
    try:
        units = server.tactic_invocations(file_path)
    except Exception as e:
        # print(f"Error: {e}")
        error_files.append(f"Error in {file_path} with {e}")
    else:
        for i, unit in enumerate(units):
            for inv in unit.invocations:
                res.append((inv.before, inv.tactic, inv.after))
    server.gc()
    return res, error_files

def trace_mathlib():
    project_path = "/working_directory/mathlib4"
    TARGET_FILE = "Mathlib.lean"
    files = []
    with open(os.path.join(project_path, TARGET_FILE), 'r') as f:
        entrys = f.readlines()
        for entry in entrys:
            if entry.startswith("import") and "Mathlib" in entry:
                file = entry.strip("import").strip("\n").strip().replace(".", "/") + ".lean"
                files.append(os.path.join(project_path, file))
    
    with multiprocessing.Pool(os.cpu_count()) as p:
        res = []
        errors = []
        for result in tqdm(p.imap_unordered(trace_file, files), total=len(files), desc="Tracing Files"):
            res.extend(result)
            errors.extend(result[1])
    return res, errors


if __name__ == "__main__":
    results, errors = trace_mathlib()
    print(f"Total invocations: {len(results)}")
    print(f"Error files: {len(errors)}")
    print(errors[0])
```
# Expected Output
```
Total invocations: 9690
Error files: 2212
Error in /home/v-shaonanwu/lean_repos/mathlib4/Mathlib/Algebra/Algebra/Defs.lean with Cannot decode: libc++abi: terminating due to uncaught exception of type lean::exception: cannot evaluate `[init]` declaration 'Mathlib.AssertNotExist.assertExistsExt' in the same module
```
# Summary
1. Can you help me to resolve this issue? The Leandojo tool can extract around 280k state-tactic pairs from Mathlib (@v4.8.0 rc1). The performance of PantoGraph is a little poor compared with existing tools. 
2. Tracing mathlib is an important practice for data-tracing tools in NTP research. Maybe it should be added to the Examples of this repo? 
3. If this tool is capable of tracing most existing repos on Github, it will be much better while it is hard to handle so many different Lean versions.

**Comment by wclsn** [comment]
Sorry, I made a mistake in the value of `imports` argument.  Now the code below works except a minor issue (I assume it is not rooted in the PantoGraph.):
```python
def trace_file(file):
    file_path, entry = file
    res = []
    error_files = []
    try:
        server = Server(imports=[entry], project_path="working_directory/lean_repos/mathlib4")
        units = server.tactic_invocations(file_path)
    except Exception as e:
        print(f"Error: {e}")
        error_files.append(f"Error in {file_path} with {e}")
    else:
        for i, unit in enumerate(units):
            for inv in unit.invocations:
                res.append((inv.before, inv.tactic, inv.after))
    finally:
        if "server" in locals():
            server.gc()
    return res, error_files

def trace_mathlib():
    project_path = "working_directory/lean_repos/mathlib4"
    TARGET_FILE = "Mathlib.lean"
    files = []
    with open(os.path.join(project_path, TARGET_FILE), 'r') as f:
        entrys = f.readlines()
        for entry in entrys:
            if entry.startswith("import") and "Mathlib" in entry:
                entry = entry.strip("import").strip("\n").strip()
                file = entry.replace(".", "/") + ".lean"
                files.append((os.path.join(project_path, file), entry))
    
    with multiprocessing.Pool(os.cpu_count()) as p:
        res = []
        errors = []
        for result in tqdm(p.imap_unordered(trace_file, files), total=len(files), desc="Tracing Files"):
            res.extend(result[0])
            errors.extend(result[1])
    return res, errors
```
# Expected Output
Error files: 1
Error in working_directory/lean_repos/mathlib4/Mathlib/Tactic/LinearCombination'.lean with Server failed to emit ready signal: uncaught exception: import failed, trying to import module with anonymous name
; Maybe the project needs to be rebuilt

**Comment by lenianiva** [comment]
I just got a chance to look at this issue. If `lake` says the project needs to be rebuilt, then maybe rebuild mathlib?

If this is not rooted in Pantograph, can I close the issue?

**Comment by wclsn** [comment]
> I just got a chance to look at this issue. If `lake` says the project needs to be rebuilt, then maybe rebuild mathlib?
> 
> If this is not rooted in Pantograph, can I close the issue?

Yes. This issue should be closed.
