### ISSUE TITLE
Theorems from other datasets (minif2f) not working with PyPantograph

### ISSUE THREAD

**Issue by slimtune2023** [lenianiva/PyPantograph#8]
I was trying to test the pantograph server functions with theorems from other datasets, like the minif2f dataset, but I always get ServerError when I use the goal_start function from server.py. I was wondering what the specific format theorems should be in when I use the pantograph goal_start method with them. Thank you!

Also, here are some example theorems which the goal_start method was not working for:
1. (y : Nat) -> 7 * (3 * y + 2) = 21 * y + 14
2. (x : ℝ), (y : ℚ), (irrational x) -> irrational (x + y)
3. (a b : ℝ), (h₁ : (a * b)=180), (h₂ : 2 * (a + b)=54) -> (a^2 + b^2) = 369

**Comment by lenianiva** [comment]
MiniF2F is Lean 3. You'll have to manually translate that into Lean 4.

**Comment by slimtune2023** [comment]
I didn't realize it was Lean 3. Thank you for letting me know!
