### ISSUE TITLE
Documentation of PyPantograph

### ISSUE THREAD

**Issue by slimtune2023** [lenianiva/PyPantograph#9]
Hello! I was wondering if there was any documentation available for using the pantograph server, specifically on the different possible errors one can get when using it. Thank you!

**Comment by lenianiva** [comment]
There isn't beyond what is provided in the `Exception` object that `ServerError` inherits from.

**Comment by slimtune2023** [comment]
Thank you! I will use the error messages for now.

**Comment by lenianiva** [comment]
There are documentations now, along with examples.
